/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.ditdah;

import io.francitoshi.ditdah.Main;
import org.junit.jupiter.api.Test;

class MainTest 
{
    @Test void testMain() 
    {
        Main.main("-L");
    }
}
